### ISSUE TITLE
Develop the new concept for the project

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/hackfornepal#6]
Brainstorm the new project concept to run the initiative in a more sustainable and diverse way.

**TODO**
- [ ] Setup working folder
- [ ] Draft the basic idea
- [ ] Discuss and take feedback on the idea
- [ ] Put the idea OPEN for the public comment
